# Generated by Django 2.2 on 2019-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuffixWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='附加词名称')),
                ('catagery', models.IntegerField(default=0, verbose_name='分类')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '附加词',
                'verbose_name_plural': '附加词',
            },
        ),
    ]
