# Generated by Django 2.2 on 2019-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_spider'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='spiderType',
            field=models.IntegerField(choices=[(0, '影视爬虫'), (1, '音乐爬虫')], default=0, verbose_name='爬虫类型'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='dictParameters',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='字典参数'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='keywordParameters',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='关键词参数'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='status',
            field=models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, verbose_name='状态'),
        ),
    ]
